#!/usr/bin/env bash
#
# A wizard walks a human through setting up Turso SQLite and Vercel Deployment.
# Generated by the /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=3

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then nohup wslview "$url" </dev/null >/dev/null 2>&1 &
    elif command -v explorer.exe >/dev/null 2>&1; then nohup explorer.exe "$url" </dev/null >/dev/null 2>&1 &
    elif command -v xdg-open    >/dev/null 2>&1; then nohup xdg-open "$url" </dev/null >/dev/null 2>&1 &
    elif command -v open        >/dev/null 2>&1; then nohup open "$url" </dev/null >/dev/null 2>&1 &
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  if [[ -r /dev/tty ]]; then
    read -r _ </dev/tty || true
  else
    read -r _ || true
  fi
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  if [[ -r /dev/tty ]]; then
    read -r reply </dev/tty || true
  else
    read -r reply || true
  fi
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  if [[ -r /dev/tty ]]; then
    read -r input </dev/tty || true
  else
    read -r input || true
  fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  if [[ -r /dev/tty ]]; then
    read -rs input </dev/tty || true
  else
    read -rs input || true
  fi
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  printf '\n%sNext Steps:%s\n' "$BOLD" "$RESET"
  printf '  1. Push code to your remote GitHub repo\n'
  printf '  2. Import repository on Vercel and paste environment variables from .env\n'
  printf '  3. Your storefront will be live at https://your-project.vercel.app\n\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

banner "Heritage Bronze Storefront · Deployment & DB Setup"

# Stage 1: Turso Edge Database
stage "Turso Database Provisioning"
say "We will grab your Turso edge SQLite connection URL and auth token."
open_url "https://turso.tech/app"
step "Log in or sign up at Turso (free tier includes 9GB and 500M row reads)."
step "Click 'Create database', name it e.g. 'bronze-storefront'."
step "Copy the Database URL (starts with libsql:// or https://)."
ask DATABASE_URL "Paste DATABASE_URL (or file:local.db for local file):"
write_env DATABASE_URL "$DATABASE_URL"

if [[ "$DATABASE_URL" =~ ^libsql:// || "$DATABASE_URL" =~ ^https:// ]]; then
  step "Generate an Auth Token in Turso database settings and copy it."
  ask_secret DATABASE_AUTH_TOKEN "Paste DATABASE_AUTH_TOKEN:"
  write_env DATABASE_AUTH_TOKEN "$DATABASE_AUTH_TOKEN"
else
  write_env DATABASE_AUTH_TOKEN ""
fi

# Stage 2: Storefront Admin Contact
stage "Admin & Communication Config"
say "These details configure the off-platform WhatsApp/Email links and admin authorization."
ask ADMIN_EMAILS "Enter admin email whitelist (comma-separated):"
write_env ADMIN_EMAILS "$ADMIN_EMAILS"

ask ADMIN_PHONE "Enter artisan phone for WhatsApp/Calls (e.g. +919876543210):"
write_env ADMIN_PHONE "$ADMIN_PHONE"

ask ADMIN_EMAIL "Enter public customer service email (e.g. craft@heritagebronze.in):"
write_env ADMIN_EMAIL "$ADMIN_EMAIL"

# Stage 3: Vercel Project
stage "Vercel Project & Auto-Deploy"
say "Now we connect this repository to Vercel."
open_url "https://vercel.com/new"
step "Select your Git repository and click 'Import'."
step "In 'Environment Variables', copy the variables from your .env file:"
step "  - DATABASE_URL"
step "  - DATABASE_AUTH_TOKEN (if using Turso cloud)"
step "  - ADMIN_EMAILS"
step "  - ADMIN_PHONE"
step "  - ADMIN_EMAIL"
step "Click 'Deploy'."
pause "Press Enter once deployment has been triggered on Vercel"

finish
